In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [3]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [4]:
df.shape

(898, 35)

In [5]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [6]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [7]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [8]:
from sklearn.preprocessing import StandardScaler , LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test , y_train, y_test = train_test_split(
    X,y, test_size=0.2 , random_state = 42
    )

In [10]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### ANN

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [12]:
X_train_tensor = torch.tensor(X_train_scaled,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [13]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [14]:
#Build our Mode

In [15]:
class ANN(nn.Module):
  def __init__(self):
    super(ANN,self).__init__()

    self.model = nn.Sequential(

        #nn.Linear(input feature , output feature)
        nn.Linear(X_train.shape[1],64),
        nn.ReLU(),
        nn.Linear(64,64),
        nn.ReLU(),
        nn.Linear(64,7)
    )

  def forward(self,x):
      return self.model(x)

In [17]:
model = ANN()
# loss and optim

criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [20]:
# Train the NN

epochs = 100
for epoch in range (epochs):
  model.train()

  running_loss = 0.0

  for xb,yb in train_loader:
    optimizer.zero_grad()

    outputs = model(xb)
    loss = criteria(outputs,yb)
    loss.backward()
    optimizer.step()# param update

    running_loss += loss.item()

    train_loss = running_loss/ len(train_loader)

    print(f"epoch = {epoch}/{epochs}, loss = {train_loss}")

epoch = 0/100, loss = 0.08335727194081181
epoch = 0/100, loss = 0.16516216941501782
epoch = 0/100, loss = 0.245264426521633
epoch = 0/100, loss = 0.32487925239231275
epoch = 0/100, loss = 0.4020134728887807
epoch = 0/100, loss = 0.47850899592689844
epoch = 0/100, loss = 0.5565483310948247
epoch = 0/100, loss = 0.6317365014034769
epoch = 0/100, loss = 0.7055224594862565
epoch = 0/100, loss = 0.78073091092317
epoch = 0/100, loss = 0.8553719313248344
epoch = 0/100, loss = 0.9292267146317855
epoch = 0/100, loss = 1.0008864195450493
epoch = 0/100, loss = 1.067815671796384
epoch = 0/100, loss = 1.1366536098977793
epoch = 0/100, loss = 1.2076154066168743
epoch = 0/100, loss = 1.2773464710816094
epoch = 0/100, loss = 1.338657462078592
epoch = 0/100, loss = 1.400035516075466
epoch = 0/100, loss = 1.4589657472527546
epoch = 0/100, loss = 1.5196128202521282
epoch = 0/100, loss = 1.5819144922754038
epoch = 0/100, loss = 1.6428355704183164
epoch = 1/100, loss = 0.06003041371055271
epoch = 1/100, loss = 0.11782345046167789
epoch = 1/100, loss = 0.16525350446286408
epoch = 1/100, loss = 0.2262666018112846
epoch = 1/100, loss = 0.28451670252758526
epoch = 1/100, loss = 0.3314044320065042
epoch = 1/100, loss = 0.3740021094031956
epoch = 1/100, loss = 0.4184353662573773
epoch = 1/100, loss = 0.47267310515693994
epoch = 1/100, loss = 0.5252223014831543
epoch = 1/100, loss = 0.5751811525096064
epoch = 1/100, loss = 0.6168046956476958
epoch = 1/100, loss = 0.6560542272484821
epoch = 1/100, loss = 0.6960311272869939
epoch = 1/100, loss = 0.7342403997545657
epoch = 1/100, loss = 0.762861298478168
epoch = 1/100, loss = 0.7963595519895139
epoch = 1/100, loss = 0.839641915715259
epoch = 1/100, loss = 0.8784255800039872
epoch = 1/100, loss = 0.9225071798200193
epoch = 1/100, loss = 0.9543361767478611
epoch = 1/100, loss = 0.9875103779461073
epoch = 1/100, loss = 1.043173813301584
epoch = 2/100, loss = 0.03405627219573311
epoch = 2/100, loss = 0.0683397624803626
epoch = 2/100, loss = 0.10680741849152939
epoch = 2/100, loss = 0.1368771273156871
epoch = 2/100, loss = 0.17845992420030676
epoch = 2/100, loss = 0.21165344248647275
epoch = 2/100, loss = 0.24301067901694257
epoch = 2/100, loss = 0.2681366205215454
epoch = 2/100, loss = 0.3074060548906741
epoch = 2/100, loss = 0.34196134494698566
epoch = 2/100, loss = 0.3703792665315711
epoch = 2/100, loss = 0.4054107251374618
epoch = 2/100, loss = 0.4350981401360553
epoch = 2/100, loss = 0.4606605405392854
epoch = 2/100, loss = 0.4837681728860606
epoch = 2/100, loss = 0.5125573044237883
epoch = 2/100, loss = 0.5351133683453435
epoch = 2/100, loss = 0.5687652593073638
epoch = 2/100, loss = 0.6033210676649342
epoch = 2/100, loss = 0.6280124317044797
epoch = 2/100, loss = 0.6573932689169179
epoch = 2/100, loss = 0.6793184591376263
epoch = 2/100, loss = 0.6997878538525623
epoch = 3/100, loss = 0.02297580501307612
epoch = 3/100, loss = 0.052204645198324455
epoch = 3/100, loss = 0.07242957794147989
epoch = 3/100, loss = 0.10301442379536836
epoch = 3/100, loss = 0.1269215306510096
epoch = 3/100, loss = 0.14903052345566128
epoch = 3/100, loss = 0.17774988386941992
epoch = 3/100, loss = 0.20225074109823807
epoch = 3/100, loss = 0.2271505840446638
epoch = 3/100, loss = 0.25148887090061023
epoch = 3/100, loss = 0.27891458765320154
epoch = 3/100, loss = 0.3032312380230945
epoch = 3/100, loss = 0.3120883055355238
epoch = 3/100, loss = 0.3447036509928496
epoch = 3/100, loss = 0.37677750639293506
epoch = 3/100, loss = 0.3929017600805863
epoch = 3/100, loss = 0.40790977426197217
epoch = 3/100, loss = 0.42383906374806946
epoch = 3/100, loss = 0.4455454725286235
epoch = 3/100, loss = 0.4635204789431199
epoch = 3/100, loss = 0.4932406194832014
epoch = 3/100, loss = 0.5171353363472483
epoch = 3/100, loss = 0.5425198324348616
epoch = 4/100, loss = 0.023060456566188648
epoch = 4/100, loss = 0.03909607166829317
epoch = 4/100, loss = 0.06226820142372795
epoch = 4/100, loss = 0.08189170775206192
epoch = 4/100, loss = 0.10202587687450906
epoch = 4/100, loss = 0.12866537985594376
epoch = 4/100, loss = 0.14327260851860046
epoch = 4/100, loss = 0.16802355906237726
epoch = 4/100, loss = 0.18751464330631754
epoch = 4/100, loss = 0.21300632668578107
epoch = 4/100, loss = 0.23003322533939197
epoch = 4/100, loss = 0.24677465143411056
epoch = 4/100, loss = 0.26425241776134656
epoch = 4/100, loss = 0.2807990869750147
epoch = 4/100, loss = 0.30178456461947895
epoch = 4/100, loss = 0.32798193848651386
epoch = 4/100, loss = 0.3417560963527016
epoch = 4/100, loss = 0.35998807912287506
epoch = 4/100, loss = 0.3806733333546182
epoch = 4/100, loss = 0.39896252362624457
epoch = 4/100, loss = 0.41742030822712445
epoch = 4/100, loss = 0.437085852674816
epoch = 4/100, loss = 0.4500389358271723
epoch = 5/100, loss = 0.014140088921007902
epoch = 5/100, loss = 0.029674088177473648
epoch = 5/100, loss = 0.05084630976552549
epoch = 5/100, loss = 0.06611961385478145
epoch = 5/100, loss = 0.07976328160451807
epoch = 5/100, loss = 0.10109224138052567
epoch = 5/100, loss = 0.1135083424008411
epoch = 5/100, loss = 0.13305362281591995
epoch = 5/100, loss = 0.15135456816009854
epoch = 5/100, loss = 0.16778914565625397
epoch = 5/100, loss = 0.18493078195530435
epoch = 5/100, loss = 0.20267216407734415
epoch = 5/100, loss = 0.22532779626224353
epoch = 5/100, loss = 0.248555117327234
epoch = 5/100, loss = 0.2612412584864575
epoch = 5/100, loss = 0.2827268631561943
epoch = 5/100, loss = 0.29893218693525897
epoch = 5/100, loss = 0.3231523995814116
epoch = 5/100, loss = 0.33868523654730426
epoch = 5/100, loss = 0.3597426932791005
epoch = 5/100, loss = 0.37351154244464374
epoch = 5/100, loss = 0.38782894093057385
epoch = 5/100, loss = 0.399034110100373
epoch = 6/100, loss = 0.014584183692932129
epoch = 6/100, loss = 0.02604860844819442
epoch = 6/100, loss = 0.04179454756819684
epoch = 6/100, loss = 0.0585185082062431
epoch = 6/100, loss = 0.06960352996121281
epoch = 6/100, loss = 0.09155776578447093
epoch = 6/100, loss = 0.11111198430475981
epoch = 6/100, loss = 0.12405583780744801
epoch = 6/100, loss = 0.1342108191355415
epoch = 6/100, loss = 0.1540985036155452
epoch = 6/100, loss = 0.16783938524515732
epoch = 6/100, loss = 0.19162045160065527
epoch = 6/100, loss = 0.20648045449153238
epoch = 6/100, loss = 0.2210932212031406
epoch = 6/100, loss = 0.2296566289404164
epoch = 6/100, loss = 0.2474123952181443
epoch = 6/100, loss = 0.2693653301052425
epoch = 6/100, loss = 0.28498132202936255
epoch = 6/100, loss = 0.29342865296032117
epoch = 6/100, loss = 0.3069993127947268
epoch = 6/100, loss = 0.32454323250314465
epoch = 6/100, loss = 0.33669341517531354
epoch = 6/100, loss = 0.35707512627477234
epoch = 7/100, loss = 0.009022800818733547
epoch = 7/100, loss = 0.023186065580533897
epoch = 7/100, loss = 0.031533840557803276
epoch = 7/100, loss = 0.04422561824321747
epoch = 7/100, loss = 0.0574322751034861
epoch = 7/100, loss = 0.0724866033896156
epoch = 7/100, loss = 0.08522827793722568
epoch = 7/100, loss = 0.09996556911779486
epoch = 7/100, loss = 0.11565168461074
epoch = 7/100, loss = 0.1287191672169644
epoch = 7/100, loss = 0.1459962900566018
epoch = 7/100, loss = 0.15975667017957437
epoch = 7/100, loss = 0.17313455563524496
epoch = 7/100, loss = 0.19422305342943771
epoch = 7/100, loss = 0.2082996789527976
epoch = 7/100, loss = 0.21619573041148807
epoch = 7/100, loss = 0.2336990010479222
epoch = 7/100, loss = 0.247646728935449
epoch = 7/100, loss = 0.2666557515444963
epoch = 7/100, loss = 0.27999192411484924
epoch = 7/100, loss = 0.29208470751409943
epoch = 7/100, loss = 0.30760418008203094
epoch = 7/100, loss = 0.32223592957724695
epoch = 8/100, loss = 0.008997203863185385
epoch = 8/100, loss = 0.017867149218269016
epoch = 8/100, loss = 0.03018959967986397
epoch = 8/100, loss = 0.043282165475513626
epoch = 8/100, loss = 0.05532197200733682
epoch = 8/100, loss = 0.06603266493133876
epoch = 8/100, loss = 0.07778073393780252
epoch = 8/100, loss = 0.09135026128395744
epoch = 8/100, loss = 0.10429222687431004
epoch = 8/100, loss = 0.11540225407351619
epoch = 8/100, loss = 0.13007149489029593
epoch = 8/100, loss = 0.13911226262216983
epoch = 8/100, loss = 0.1559281686077947
epoch = 8/100, loss = 0.16958272716273431
epoch = 8/100, loss = 0.18285340589025748
epoch = 8/100, loss = 0.2009656442248303
epoch = 8/100, loss = 0.21692671464837116
epoch = 8/100, loss = 0.22485705756622812
epoch = 8/100, loss = 0.24505629034146018
epoch = 8/100, loss = 0.2568652739991312
epoch = 8/100, loss = 0.2711795108473819
epoch = 8/100, loss = 0.2814494753661363
epoch = 8/100, loss = 0.2946848538906678
epoch = 9/100, loss = 0.013293811808461729
epoch = 9/100, loss = 0.023962671342103378
epoch = 9/100, loss = 0.031639864263327225
epoch = 9/100, loss = 0.04176661177821781
epoch = 9/100, loss = 0.05394010116224703
epoch = 9/100, loss = 0.06675610140613887
epoch = 9/100, loss = 0.07652325863423555
epoch = 9/100, loss = 0.08952792831089186
epoch = 9/100, loss = 0.10214137383129286
epoch = 9/100, loss = 0.11770996710528499
epoch = 9/100, loss = 0.13494347100672516
epoch = 9/100, loss = 0.14284858561080435
epoch = 9/100, loss = 0.15760349385116412
epoch = 9/100, loss = 0.16467775469240936
epoch = 9/100, loss = 0.17302438616752625
epoch = 9/100, loss = 0.1798079920851666
epoch = 9/100, loss = 0.18643623396106387
epoch = 9/100, loss = 0.19623366127843442
epoch = 9/100, loss = 0.21012696623802185
epoch = 9/100, loss = 0.2264392077922821
epoch = 9/100, loss = 0.24466751839803613
epoch = 9/100, loss = 0.2561371507851974
epoch = 9/100, loss = 0.2685209175814753
epoch = 10/100, loss = 0.008372274429901787
epoch = 10/100, loss = 0.022914359103078426
epoch = 10/100, loss = 0.03106175816577414
epoch = 10/100, loss = 0.0434896531312362
epoch = 10/100, loss = 0.05056454694789389
epoch = 10/100, loss = 0.057470646241436836
epoch = 10/100, loss = 0.06258018152869266
epoch = 10/100, loss = 0.0758569373384766
epoch = 10/100, loss = 0.086751830642638
epoch = 10/100, loss = 0.09366524705420369
epoch = 10/100, loss = 0.10266364819329718
epoch = 10/100, loss = 0.12259587548349214
epoch = 10/100, loss = 0.13840931297644324
epoch = 10/100, loss = 0.1460455400140389
epoch = 10/100, loss = 0.1606793873336004
epoch = 10/100, loss = 0.17332298114247943
epoch = 10/100, loss = 0.18391543011302533
epoch = 10/100, loss = 0.20082653637813486
epoch = 10/100, loss = 0.21249255052079324
epoch = 10/100, loss = 0.22637978617263876
epoch = 10/100, loss = 0.234655875550664
epoch = 10/100, loss = 0.242935165438963
epoch = 10/100, loss = 0.25941949726446817
epoch = 11/100, loss = 0.009664440284604612
epoch = 11/100, loss = 0.02023424013801243
epoch = 11/100, loss = 0.03351041026737379
epoch = 11/100, loss = 0.04094943533773008
epoch = 11/100, loss = 0.04781742199607517
epoch = 11/100, loss = 0.056548638188320656
epoch = 11/100, loss = 0.06728934205096701
epoch = 11/100, loss = 0.08338696801144144
epoch = 11/100, loss = 0.08981447180976039
epoch = 11/100, loss = 0.10608976755453192
epoch = 11/100, loss = 0.11402422902376755
epoch = 11/100, loss = 0.12483118992784749
epoch = 11/100, loss = 0.1416475507228271
epoch = 11/100, loss = 0.15490007594875668
epoch = 11/100, loss = 0.16282351055870886
epoch = 11/100, loss = 0.17808580074621283
epoch = 11/100, loss = 0.18687241427276446
epoch = 11/100, loss = 0.19761043981365536
epoch = 11/100, loss = 0.20569113998309427
epoch = 11/100, loss = 0.2120494764784108
epoch = 11/100, loss = 0.22114339470863342
epoch = 11/100, loss = 0.22984539620254352
epoch = 11/100, loss = 0.2383619520975196
epoch = 12/100, loss = 0.007378716831621917
epoch = 12/100, loss = 0.016145840935085132
epoch = 12/100, loss = 0.027028841816860695
epoch = 12/100, loss = 0.03252836867519047
epoch = 12/100, loss = 0.04253999176232711
epoch = 12/100, loss = 0.052126257963802505
epoch = 12/100, loss = 0.06946446131105008
epoch = 12/100, loss = 0.07578431005063264
epoch = 12/100, loss = 0.08799878410671068
epoch = 12/100, loss = 0.09734789897566257
epoch = 12/100, loss = 0.10382064853025519
epoch = 12/100, loss = 0.11574861083341681
epoch = 12/100, loss = 0.12098106255997783
epoch = 12/100, loss = 0.13235850599796875
epoch = 12/100, loss = 0.14043313232452972
epoch = 12/100, loss = 0.14885323494672775
epoch = 12/100, loss = 0.15727138357317966
epoch = 12/100, loss = 0.17220961367306503
epoch = 12/100, loss = 0.18309393233579138
epoch = 12/100, loss = 0.19878428235002185
epoch = 12/100, loss = 0.2054757679934087
epoch = 12/100, loss = 0.21396566700676214
epoch = 12/100, loss = 0.2179553997905358
epoch = 13/100, loss = 0.007351327849471051
epoch = 13/100, loss = 0.015545453066411226
epoch = 13/100, loss = 0.021385298474975254
epoch = 13/100, loss = 0.028218255742736485
epoch = 13/100, loss = 0.03528273753497912
epoch = 13/100, loss = 0.04527867747389752
epoch = 13/100, loss = 0.05094183009603749
epoch = 13/100, loss = 0.05738762280215388
epoch = 13/100, loss = 0.06989209548286769
epoch = 13/100, loss = 0.07861837550349858
epoch = 13/100, loss = 0.0886537095774775
epoch = 13/100, loss = 0.09682547916536746
epoch = 13/100, loss = 0.10422863066196442
epoch = 13/100, loss = 0.1203042974938517
epoch = 13/100, loss = 0.13098953599515167
epoch = 13/100, loss = 0.1368546038866043
epoch = 13/100, loss = 0.1466680829939635
epoch = 13/100, loss = 0.15290951858396115
epoch = 13/100, loss = 0.16800788951956708
epoch = 13/100, loss = 0.1760030615588893
epoch = 13/100, loss = 0.1850956451633702
epoch = 13/100, loss = 0.1966923598362052
epoch = 13/100, loss = 0.20734966449115588
epoch = 14/100, loss = 0.0074299917272899465
epoch = 14/100, loss = 0.014392271637916565
epoch = 14/100, loss = 0.025406247247820316
epoch = 14/100, loss = 0.03719914672167405
epoch = 14/100, loss = 0.04994759157947872
epoch = 14/100, loss = 0.058892561689667076
epoch = 14/100, loss = 0.06482135796028635
epoch = 14/100, loss = 0.07440262579399606
epoch = 14/100, loss = 0.07837544575981471
epoch = 14/100, loss = 0.08784364811752153
epoch = 14/100, loss = 0.09348797539006108
epoch = 14/100, loss = 0.10252084939376167
epoch = 14/100, loss = 0.11268766030021336
epoch = 14/100, loss = 0.1196013015249501
epoch = 14/100, loss = 0.12386072394640549
epoch = 14/100, loss = 0.13337175224138342
epoch = 14/100, loss = 0.14426549621250317
epoch = 14/100, loss = 0.1492520444419073
epoch = 14/100, loss = 0.16477678942939508
epoch = 14/100, loss = 0.1773887850020243
epoch = 14/100, loss = 0.180408648174742
epoch = 14/100, loss = 0.19115209709043088
epoch = 14/100, loss = 0.19770971134952878
epoch = 15/100, loss = 0.005967858692874079
epoch = 15/100, loss = 0.010399909447068754
epoch = 15/100, loss = 0.024257880514082703
epoch = 15/100, loss = 0.032871111903501594
epoch = 15/100, loss = 0.04969678398059762
epoch = 15/100, loss = 0.05910557800013086
epoch = 15/100, loss = 0.06870495657558026
epoch = 15/100, loss = 0.07532617546941923
epoch = 15/100, loss = 0.08237358636182288
epoch = 15/100, loss = 0.08995793986579646
epoch = 15/100, loss = 0.09836321000171744
epoch = 15/100, loss = 0.10056334701569183
epoch = 15/100, loss = 0.11450655531624089
epoch = 15/100, loss = 0.12081857381955437
epoch = 15/100, loss = 0.12485856919184975
epoch = 15/100, loss = 0.1300310466600501
epoch = 15/100, loss = 0.14102531127307727
epoch = 15/100, loss = 0.14945438439431397
epoch = 15/100, loss = 0.15788655566132587
epoch = 15/100, loss = 0.16293073056832605
epoch = 15/100, loss = 0.17532082452722217
epoch = 15/100, loss = 0.17855409273634787
epoch = 15/100, loss = 0.19299323241347852
epoch = 16/100, loss = 0.004680192017036936
epoch = 16/100, loss = 0.009812424688235573
epoch = 16/100, loss = 0.021260199015555176
epoch = 16/100, loss = 0.024666177837745003
epoch = 16/100, loss = 0.029390750371891518
epoch = 16/100, loss = 0.03910719376543294
epoch = 16/100, loss = 0.0505966719077981
epoch = 16/100, loss = 0.06565064774907153
epoch = 16/100, loss = 0.06900656093721805
epoch = 16/100, loss = 0.07749493873637656
epoch = 16/100, loss = 0.0861718738856523
epoch = 16/100, loss = 0.08888049148347067
epoch = 16/100, loss = 0.09466406751586043
epoch = 16/100, loss = 0.10085786474139793
epoch = 16/100, loss = 0.11269128759918005
epoch = 16/100, loss = 0.1175161293991234
epoch = 16/100, loss = 0.125035524206317
epoch = 16/100, loss = 0.13459883484503496
epoch = 16/100, loss = 0.13946514042175334
epoch = 16/100, loss = 0.1571411245866962
epoch = 16/100, loss = 0.1638551887286746
epoch = 16/100, loss = 0.17320852775288664
epoch = 16/100, loss = 0.18225067675761555
epoch = 17/100, loss = 0.009334180666052776
epoch = 17/100, loss = 0.020419080620226654
epoch = 17/100, loss = 0.03197533799254376
epoch = 17/100, loss = 0.03751217023186062
epoch = 17/100, loss = 0.041770103509011475
epoch = 17/100, loss = 0.046438009194705795
epoch = 17/100, loss = 0.053205689010412796
epoch = 17/100, loss = 0.0632420512645141
epoch = 17/100, loss = 0.0684453621506691
epoch = 17/100, loss = 0.07679757702609767
epoch = 17/100, loss = 0.08239938415910887
epoch = 17/100, loss = 0.09687770352415416
epoch = 17/100, loss = 0.09922052093822023
epoch = 17/100, loss = 0.1066259438900844
epoch = 17/100, loss = 0.11435072399351907
epoch = 17/100, loss = 0.12187586222653804
epoch = 17/100, loss = 0.1279780024095722
epoch = 17/100, loss = 0.1407326357844083
epoch = 17/100, loss = 0.1483837231669737
epoch = 17/100, loss = 0.15480524836027104
epoch = 17/100, loss = 0.16302566700007604
epoch = 17/100, loss = 0.170217698197002
epoch = 17/100, loss = 0.17460297938922179
epoch = 18/100, loss = 0.014038231061852497
epoch = 18/100, loss = 0.02579209856365038
epoch = 18/100, loss = 0.027755274882783062
epoch = 18/100, loss = 0.04112310658978379
epoch = 18/100, loss = 0.04670792056814484
epoch = 18/100, loss = 0.05139922787961752
epoch = 18/100, loss = 0.06059119639837224
epoch = 18/100, loss = 0.07086129437970079
epoch = 18/100, loss = 0.08058188094393066
epoch = 18/100, loss = 0.08819193959884021
epoch = 18/100, loss = 0.09901984700042268
epoch = 18/100, loss = 0.10572638670387476
epoch = 18/100, loss = 0.109214561626963
epoch = 18/100, loss = 0.11739101730611014
epoch = 18/100, loss = 0.1264938827118148
epoch = 18/100, loss = 0.13194385478677956
epoch = 18/100, loss = 0.1410503612588281
epoch = 18/100, loss = 0.1453869182454503
epoch = 18/100, loss = 0.15147791754292406
epoch = 18/100, loss = 0.1575411527377108
epoch = 18/100, loss = 0.1637311890397383
epoch = 18/100, loss = 0.17366228689965996
epoch = 18/100, loss = 0.1808031650017137
epoch = 19/100, loss = 0.0041606759895449095
epoch = 19/100, loss = 0.007496586636356686
epoch = 19/100, loss = 0.015872575342655182
epoch = 19/100, loss = 0.020404104953226837
epoch = 19/100, loss = 0.02610312272673068
epoch = 19/100, loss = 0.032902714350949165
epoch = 19/100, loss = 0.04099909118984057
epoch = 19/100, loss = 0.04639237438854964
epoch = 19/100, loss = 0.05463871003493019
epoch = 19/100, loss = 0.06136413404475088
epoch = 19/100, loss = 0.06620289871226186
epoch = 19/100, loss = 0.07324651693520338
epoch = 19/100, loss = 0.08190026134252548
epoch = 19/100, loss = 0.0961361530682315
epoch = 19/100, loss = 0.10984245493360188
epoch = 19/100, loss = 0.11446953597276108
epoch = 19/100, loss = 0.12767140243364417
epoch = 19/100, loss = 0.13471651401208795
epoch = 19/100, loss = 0.14330514423225238
epoch = 19/100, loss = 0.14598182281074318
epoch = 19/100, loss = 0.15278445297609206
epoch = 19/100, loss = 0.1605220221630905
epoch = 19/100, loss = 0.17503104439896086
epoch = 20/100, loss = 0.0034066535856412806
epoch = 20/100, loss = 0.009433516989583555
epoch = 20/100, loss = 0.015010148286819458
epoch = 20/100, loss = 0.022000930231550465
epoch = 20/100, loss = 0.027382958842360455
epoch = 20/100, loss = 0.03380224043908327
epoch = 20/100, loss = 0.04301656782627106
epoch = 20/100, loss = 0.055531904101371765
epoch = 20/100, loss = 0.060603348781233246
epoch = 20/100, loss = 0.06600246027759883
epoch = 20/100, loss = 0.07326563220957051
epoch = 20/100, loss = 0.08007729442223259
epoch = 20/100, loss = 0.09264345920604208

In [23]:
#Evaluate

model.eval()

total = 0
correct = 0

with torch.no_grad():
  for xb,yb in test_loader:
    outputs = model(xb)  # [0.2,0.5,1.3,-0.5...] -7 vals
    _, predicted = torch.max(outputs,1)

    correct += (predicted == yb).sum().item()
    total += yb.size(0) # actual samples in each batch


print("total vals : ",total)
print("correct vals : ",correct)
print("accuracy : ",correct/total  * 100)

total vals :  180
correct vals :  170
accuracy :  94.44444444444444

In [22]:
y_test.shape

(180,)